# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_role_profile_preferred_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(
                choices=[
                    ('en', 'English'),
                    ('zh-hans', '简体中文'),
                ],
                default='en',
                help_text=(
                    'Specifies the language used by AI when generating '
                    'summaries, titles, and metadata. This is a global '
                    'setting shared across all applications.'
                ),
                max_length=10,
            ),
        ),
    ]
