# Generated by Django 5.1.4 for Lens v3.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSetting",
            fields=[
                (
                    "key",
                    models.CharField(
                        max_length=190,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value", models.JSONField(blank=True, default=dict)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MCPServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("transport", models.CharField(choices=[("url", "URL"), ("stdio", "STDIO")], max_length=16)),
                ("endpoint", models.CharField(blank=True, default="", max_length=500)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("role", models.CharField(choices=[("user", "User"), ("assistant", "Assistant"), ("system", "System")], max_length=16)),
                ("content", models.TextField(blank=True, default="")),
                ("sequence", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["sequence"]},
        ),
        migrations.CreateModel(
            name="LensNode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("status", models.CharField(choices=[("online", "Online"), ("offline", "Offline"), ("draining", "Draining")], default="offline", max_length=16)),
                ("connection_id", models.CharField(blank=True, default="", max_length=128)),
                ("workspace_path", models.CharField(blank=True, default="", max_length=500)),
                ("available_dirs", models.JSONField(blank=True, default=list)),
                ("protocol_version", models.CharField(blank=True, default="", max_length=32)),
                ("agent_version", models.CharField(blank=True, default="", max_length=64)),
                ("tasks", models.JSONField(blank=True, default=list)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("enrollment_status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], default="pending", max_length=16)),
                ("auth_token_hash", models.CharField(blank=True, default="", max_length=128)),
                ("token_issued_at", models.DateTimeField(blank=True, null=True)),
                ("token_revoked", models.BooleanField(default=False)),
                ("last_authenticated_at", models.DateTimeField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["status"], name="lens_lensnode_status_idx"),
                    models.Index(fields=["enrollment_status"], name="lens_lensnode_enroll_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("definition", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("source_type", models.CharField(choices=[("git", "Git"), ("feishu", "Feishu"), ("jira", "Jira")], max_length=32)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("sync_policy", models.JSONField(blank=True, default=dict)),
                ("target_path", models.CharField(blank=True, default="", max_length=500)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled"), ("error", "Error")], default="active", max_length=16)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["status"], name="lens_datasource_status_idx")],
            },
        ),
        migrations.CreateModel(
            name="Assistant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("selected_task", models.CharField(max_length=160)),
                ("selected_dirs", models.JSONField(blank=True, default=list)),
                ("preprocess_model_ref", models.UUIDField(blank=True, null=True)),
                ("multimodal_model_ref", models.UUIDField(blank=True, null=True)),
                ("agent_model_ref", models.UUIDField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("active", "Active"), ("disabled", "Disabled")], default="active", max_length=16)),
                ("lensnode", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="assistants", to="lens.lensnode")),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["lensnode"], name="lens_assistant_lensnode_idx")],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("status", models.CharField(choices=[("active", "Active"), ("archived", "Archived")], default="active", max_length=16)),
                ("assistant", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lens.assistant")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="Run",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("running", "Running"), ("streaming", "Streaming"), ("done", "Done"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="queued", max_length=16)),
                ("metering_ref", models.UUIDField(blank=True, null=True)),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_message", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="request_runs", to="lens.message")),
                ("lensnode", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="runs", to="lens.lensnode")),
                ("output_message", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="response_runs", to="lens.message")),
                ("session", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lens.session")),
            ],
            options={"ordering": ["-started_at", "-created_at"]},
        ),
        migrations.AddField(
            model_name="message",
            name="run",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="lens.run"),
        ),
        migrations.AddField(
            model_name="message",
            name="session",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lens.session"),
        ),
        migrations.CreateModel(
            name="AssistantSkill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True)),
                ("load_config", models.JSONField(blank=True, default=dict)),
                ("assistant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="skill_bindings", to="lens.assistant")),
                ("skill", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lens.skill")),
            ],
            options={"unique_together": {("assistant", "skill")}},
        ),
        migrations.CreateModel(
            name="AssistantMCP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enabled", models.BooleanField(default=True)),
                ("load_config", models.JSONField(blank=True, default=dict)),
                ("assistant", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="mcp_bindings", to="lens.assistant")),
                ("mcp", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lens.mcpserver")),
            ],
            options={"unique_together": {("assistant", "mcp")}},
        ),
        migrations.CreateModel(
            name="RunExecution",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("task", models.CharField(max_length=160)),
                ("loaded_skills", models.JSONField(blank=True, default=list)),
                ("loaded_mcps", models.JSONField(blank=True, default=list)),
                ("target_dirs", models.JSONField(blank=True, default=list)),
                ("status", models.CharField(choices=[("dispatched", "Dispatched"), ("running", "Running"), ("completed", "Completed"), ("failed", "Failed")], default="dispatched", max_length=16)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("lensnode", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="lens.lensnode")),
                ("run", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="execution", to="lens.run")),
            ],
            options={"indexes": [models.Index(fields=["lensnode"], name="lens_runexec_lensnode_idx")]},
        ),
        migrations.CreateModel(
            name="RunStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("step_type", models.CharField(choices=[("query_rewrite", "Query Rewrite"), ("retrieval", "Retrieval"), ("answer", "Answer"), ("stream", "Stream")], max_length=32)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("status", models.CharField(choices=[("running", "Running"), ("done", "Done"), ("failed", "Failed")], max_length=16)),
                ("sequence", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="lens.run")),
            ],
            options={
                "ordering": ["sequence"],
                "indexes": [models.Index(fields=["run", "sequence"], name="lens_runstep_run_seq_idx")],
                "unique_together": {("run", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("task_type", models.CharField(choices=[("source_sync", "Source Sync"), ("lensnode_cleanup", "LensNode Cleanup"), ("run_retention", "Run Retention"), ("lensnode_health", "LensNode Health")], max_length=32)),
                ("periodic_task_ref", models.IntegerField(blank=True, null=True)),
                ("target_type", models.CharField(blank=True, max_length=64, null=True)),
                ("target_id", models.UUIDField(blank=True, null=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.CharField(blank=True, choices=[("success", "Success"), ("failed", "Failed"), ("running", "Running")], max_length=16, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("last_metrics", models.JSONField(blank=True, default=dict)),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["task_type"], name="lens_sched_task_type_idx"),
                    models.Index(fields=["target_type", "target_id"], name="lens_sched_target_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["session", "status"], name="lens_run_session_status_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["lensnode"], name="lens_run_lensnode_idx"),
        ),
        migrations.AddConstraint(
            model_name="run",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key", ""), _negated=True),
                fields=("session", "idempotency_key"),
                name="lens_run_idem_nonempty_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["session", "sequence"], name="lens_message_session_seq_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="message",
            unique_together={("session", "sequence")},
        ),
    ]
