# Generated by Django 5.1.4 on 2026-06-07 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='postprocess_model_ref',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mcpserver',
            name='version',
            field=models.CharField(blank=True, default='1', max_length=64),
        ),
        migrations.AddField(
            model_name='skill',
            name='version',
            field=models.CharField(blank=True, default='1', max_length=64),
        ),
    ]
