# Generated by Codex for datasource LensNode execution.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0004_assistant_max_concurrency"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="lensnode",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="datasources",
                to="lens.lensnode",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[("git", "Git"), ("feishu", "Feishu")],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="datasource",
            index=models.Index(
                fields=["lensnode"],
                name="lens_datasource_lensnode_idx",
            ),
        ),
    ]
