# Generated by Codex for datasource credential storage.

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0005_datasource_lensnode"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSourceCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("github", "GitHub"),
                            ("gitlab", "GitLab"),
                            ("generic", "Generic"),
                        ],
                        default="generic",
                        max_length=32,
                    ),
                ),
                (
                    "auth_type",
                    models.CharField(
                        choices=[("https_token", "HTTPS Token")],
                        default="https_token",
                        max_length=32,
                    ),
                ),
                ("encrypted_secret", models.TextField(blank=True, default="")),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="credential",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="datasources",
                to="lens.datasourcecredential",
            ),
        ),
    ]
