# Generated by Codex for datasource sync error visibility.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0007_datasourcecredential_feishu_choices"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
    ]
