# Generated by Django 5.1.4 on 2026-06-23 02:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def set_existing_assistants_public(apps, schema_editor):
    """Keep existing assistants visible: pre-feature data stays public."""

    Assistant = apps.get_model('lens', 'Assistant')
    Assistant.objects.update(visibility='public')


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lens', '0010_sharedqa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assistant',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='private', max_length=16),
        ),
        migrations.RunPython(set_existing_assistants_public, noop),
        migrations.CreateModel(
            name='AssistantAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(default='view', max_length=16)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='lens.assistant')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_grants', to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['assistant'], name='lens_aaccess_assistant_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('group__isnull', False), ('user__isnull', True)), models.Q(('group__isnull', True), ('user__isnull', False)), _connector='OR'), name='assistant_access_group_xor_user'), models.UniqueConstraint(condition=models.Q(('group__isnull', False)), fields=('assistant', 'group'), name='uniq_assistant_group'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('assistant', 'user'), name='uniq_assistant_user')],
            },
        ),
    ]
