# Generated by Django 5.1.4 on 2026-06-24 02:09

import django.db.models.deletion
import lens.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0011_assistant_visibility_assistantaccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='runstep',
            name='step_type',
            field=models.CharField(choices=[('query_rewrite', 'Query Rewrite'), ('multimodal', 'Multimodal'), ('retrieval', 'Retrieval'), ('answer', 'Answer'), ('stream', 'Stream')], max_length=32),
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'Image')], default='image', max_length=16)),
                ('file', models.ImageField(upload_to=lens.models.message_attachment_upload_to)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=80)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lens.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='lens.session')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lens_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['message', 'order'], name='lens_attach_msg_order_idx'), models.Index(fields=['session'], name='lens_attach_session_idx')],
            },
        ),
    ]
