# Generated by Django 5.1.4 on 2026-06-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0012_alter_runstep_step_type_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
