# Generated by Codex for datasource credential endpoint binding.

from django.db import migrations, models


def populate_credential_defaults(apps, schema_editor):
    DataSourceCredential = apps.get_model("lens", "DataSourceCredential")
    for credential in DataSourceCredential.objects.all():
        updates = []
        if not credential.endpoint_url:
            if credential.provider == "github":
                credential.endpoint_url = "https://github.com"
            elif credential.provider == "gitlab":
                credential.endpoint_url = "https://gitlab.com"
            elif credential.provider == "feishu":
                credential.endpoint_url = "https://open.feishu.cn"
            else:
                credential.endpoint_url = ""
            updates.append("endpoint_url")
        if not credential.sync_scope:
            credential.sync_scope = (
                "feishu_folder"
                if credential.auth_type == "feishu_app"
                else "service"
            )
            updates.append("sync_scope")
        if credential.scope_config is None:
            credential.scope_config = {}
            updates.append("scope_config")
        if updates:
            credential.save(update_fields=updates)


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0013_run_last_activity_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasourcecredential",
            name="endpoint_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="datasourcecredential",
            name="scope_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="datasourcecredential",
            name="sync_scope",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="datasourcecredential",
            name="validated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="datasourcecredential",
            name="validation_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="datasourcecredential",
            name="validation_status",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.RunPython(
            populate_credential_defaults,
            migrations.RunPython.noop,
        ),
    ]
