# Generated by Django 5.1.4 on 2026-07-15

import django.db.models.deletion
import lens.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0017_add_general_chat_run_step_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunOutputFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=lens.models.deliverable_storage, upload_to=lens.models.run_output_file_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='lens.assistant')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='lens.message')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='lens.run')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_files', to='lens.session')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message'], name='lens_outfile_msg_idx'), models.Index(fields=['session'], name='lens_outfile_sess_idx')],
            },
        ),
    ]
