# Generated by Django 5.1.4 on 2026-07-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0018_runoutputfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lensnode',
            name='disconnected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
