# Generated by Django 5.1.4 on 2026-07-25 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0021_alter_datasourcecredential_auth_type'),
        ('lens', '0021_environmentvariableset_assistantskill_environment'),
    ]

    operations = [
    ]
