# Generated by Django 5.1.4 on 2026-07-25

import uuid

import django.db.models.deletion
import lens.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0022_merge_20260725_1058"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedQAFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("input", "Input attachment"),
                            ("output", "Output deliverable"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_uuid", models.UUIDField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        storage=lens.models.deliverable_storage,
                        upload_to=lens.models.shared_qa_file_upload_to,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                    ),
                ),
                ("byte_size", models.PositiveIntegerField(default=0)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "share",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="lens.sharedqa",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["share", "kind", "order"],
                        name="lens_sharefile_order_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("share", "kind", "source_uuid"),
                        name="lens_sharefile_source_uniq",
                    ),
                ],
            },
        ),
    ]
