# Generated by Django 5.1.4 on 2026-07-29 04:33

from django.db import migrations, models


RUN_TIMEOUT_SECONDS_BY_ROUNDS = {
    "flash": 300,
    "fast": 600,
    "balanced": 900,
    "deep": 1800,
    "max": 3600,
}


def backfill_run_timeout_snapshots(apps, schema_editor):
    """Use the best available Assistant value for existing executions."""

    run_execution = apps.get_model("lens", "RunExecution")
    for agent_rounds, run_timeout_s in RUN_TIMEOUT_SECONDS_BY_ROUNDS.items():
        run_execution.objects.filter(
            run__session__assistant__agent_rounds=agent_rounds,
            agent_rounds__isnull=True,
        ).update(
            agent_rounds=agent_rounds,
            run_timeout_s=run_timeout_s,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("lens", "0027_run_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="runexecution",
            name="agent_rounds",
            field=models.CharField(
                choices=[
                    ("flash", "极速"),
                    ("fast", "快速"),
                    ("balanced", "均衡"),
                    ("deep", "深度"),
                    ("max", "极限"),
                ],
                default=None,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="runexecution",
            name="run_timeout_s",
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="runexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("dispatched", "Dispatched"),
                    ("running", "Running"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            backfill_run_timeout_snapshots,
            migrations.RunPython.noop,
        ),
    ]
