# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0036_rundiagnostic_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='answer_language',
            field=models.CharField(
                blank=True,
                default='',
                help_text=(
                    'Answer language requested with this run; falls back '
                    "to the user's Profile.language when not provided."
                ),
                max_length=10,
            ),
        ),
    ]
