# Generated by Django 5.1.4 on 2026-09-02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


TOKEN_BUDGET_PROFILE_BY_AGENT_ROUNDS = {
    "flash": "standard",
    "fast": "standard",
    "balanced": "standard",
    "deep": "deep",
    "max": "unlimited",
}


def bind_token_budget_to_agent_rounds(apps, schema_editor):
    """Align existing Assistants with the execution strategy mapping."""

    assistant_model = apps.get_model("lens", "Assistant")
    profiles = TOKEN_BUDGET_PROFILE_BY_AGENT_ROUNDS.items()
    for agent_rounds, token_budget_profile in profiles:
        assistant_model.objects.filter(agent_rounds=agent_rounds).update(
            token_budget_profile=token_budget_profile
        )


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0046_assistant_fixed_collaboration"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("plugin_key", models.CharField(max_length=64)),
                ("endpoint", models.URLField(max_length=500)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("allowed_scope", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SecretMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("status", models.CharField(default="active", max_length=16)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="datasource",
            name="datasource_config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="datasource",
            name="plugin_key",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="datasource",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="datasources",
                to="lens.connection",
            ),
        ),
        migrations.CreateModel(
            name="SecretVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("encrypted_value", models.TextField()),
                ("status", models.CharField(default="active", max_length=16)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="lens.secretmaterial",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("datasource_sync", "Datasource Sync"),
                            ("tool_invoke", "Tool Invoke"),
                        ],
                        max_length=32,
                    ),
                ),
                ("plugin_key", models.CharField(max_length=64)),
                ("plugin_version", models.CharField(max_length=32)),
                ("protocol_version", models.PositiveIntegerField()),
                ("resolved_config", models.JSONField(default=dict)),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_snapshots",
                        to="lens.connection",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_snapshots",
                        to="lens.datasource",
                    ),
                ),
                (
                    "secret_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_snapshots",
                        to="lens.secretversion",
                    ),
                ),
                (
                    "invocation_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugin_execution_snapshots",
                        to="lens.run",
                    ),
                ),
                ("tool_key", models.CharField(blank=True, default="", max_length=128)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="connection",
            name="secret_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="connections",
                to="lens.secretversion",
            ),
        ),
        migrations.CreateModel(
            name="CredentialLease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lensnode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_leases",
                        to="lens.lensnode",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credential_leases",
                        to="lens.executionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="runexecution",
            name="loaded_plugins",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="AssistantPluginBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tools", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_bindings",
                        to="lens.assistant",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_bindings",
                        to="lens.connection",
                    ),
                ),
            ],
            options={
                "unique_together": {("assistant", "connection")},
            },
        ),
        migrations.AddConstraint(
            model_name="executionsnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("datasource__isnull", False),
                        ("invocation_id", ""),
                        ("kind", "datasource_sync"),
                        ("run__isnull", True),
                        ("tool_key", ""),
                    ),
                    models.Q(
                        ("datasource__isnull", True),
                        ("kind", "tool_invoke"),
                        ("run__isnull", False),
                        models.Q(("tool_key", ""), _negated=True),
                        models.Q(("invocation_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="lens_snapshot_owner_kind_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "tool_invoke")),
                fields=("run", "invocation_id"),
                name="lens_snap_run_invocation_uniq",
            ),
        ),
        migrations.CreateModel(
            name="PluginInvocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("datasource_sync", "Datasource Sync"),
                            ("tool_invoke", "Tool Invoke"),
                        ],
                        max_length=32,
                    ),
                ),
                ("plugin_key", models.CharField(max_length=64)),
                ("tool_key", models.CharField(blank=True, default="", max_length=128)),
                (
                    "capability",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("resource_summary", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("authorized", "Authorized"),
                            ("materialized", "Materialized"),
                        ],
                        default="authorized",
                        max_length=24,
                    ),
                ),
                ("materialized_at", models.DateTimeField(blank=True, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="plugin_invocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugin_invocations",
                        to="lens.connection",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugin_invocations",
                        to="lens.datasource",
                    ),
                ),
                (
                    "lensnode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugin_invocations",
                        to="lens.lensnode",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plugin_invocations",
                        to="lens.run",
                    ),
                ),
                (
                    "snapshot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invocation_audit",
                        to="lens.executionsnapshot",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mcp_adapters",
                to="lens.connection",
            ),
        ),
        migrations.AddField(
            model_name="mcpserver",
            name="tools",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="mcpserver",
            name="transport",
            field=models.CharField(
                choices=[
                    ("url", "URL"),
                    ("stdio", "STDIO"),
                    ("plugin", "Plugin Adapter"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="LegacyIntegrationMigration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("credential", "Credential"),
                            ("datasource", "Datasource"),
                        ],
                        max_length=16,
                    ),
                ),
                ("source_uuid", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("migrated", "Migrated"),
                            ("manual_review", "Manual Review"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_migration_records",
                        to="lens.connection",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_migration_records",
                        to="lens.datasource",
                    ),
                ),
            ],
            options={
                "ordering": ["source_kind", "source_uuid"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_kind", "source_uuid"),
                        name="lens_legacy_migration_source_uniq",
                    )
                ],
            },
        ),
        migrations.AlterField(
            model_name="datasource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("git", "Git"),
                    ("feishu", "Feishu"),
                    ("jira", "Jira"),
                    ("managed_workspace", "Managed Workspace"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="routing_mode",
            field=models.CharField(
                choices=[("direct", "Standard Mode"), ("smart", "Smart Collaboration")],
                db_index=True,
                default="direct",
                max_length=16,
            ),
        ),
        migrations.RunPython(
            bind_token_budget_to_agent_rounds,
            migrations.RunPython.noop,
        ),
    ]
