# Generated by Django 5.1.4 on 2026-09-01 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0048_plugin_credential_leases"),
    ]

    operations = [
        migrations.AddField(
            model_name="runexecution",
            name="loaded_plugins",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name="AssistantPluginBinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tools", models.JSONField(blank=True, default=list)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "assistant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plugin_bindings",
                        to="lens.assistant",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assistant_bindings",
                        to="lens.connection",
                    ),
                ),
            ],
            options={
                "unique_together": {("assistant", "connection")},
            },
        ),
    ]
