# Generated by Django 5.1.4 on 2026-09-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lens", "0049_assistant_plugin_bindings"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionsnapshot",
            name="invocation_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="executionsnapshot",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="plugin_execution_snapshots",
                to="lens.run",
            ),
        ),
        migrations.AddField(
            model_name="executionsnapshot",
            name="tool_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="executionsnapshot",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ("datasource__isnull", False),
                        ("invocation_id", ""),
                        ("kind", "datasource_sync"),
                        ("run__isnull", True),
                        ("tool_key", ""),
                    )
                    | (
                        models.Q(
                            ("datasource__isnull", True),
                            ("kind", "tool_invoke"),
                            ("run__isnull", False),
                        )
                        & ~models.Q(("tool_key", ""))
                        & ~models.Q(("invocation_id", ""))
                    )
                ),
                name="lens_snapshot_owner_kind_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionsnapshot",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "tool_invoke")),
                fields=("run", "invocation_id"),
                name="lens_snap_run_invocation_uniq",
            ),
        ),
    ]
