# Generated by Django 5.1.4 on 2026-09-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lens', '0054_datasource_jira_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistant',
            name='routing_mode',
            field=models.CharField(choices=[('direct', 'Standard Mode'), ('smart', 'Smart Collaboration')], db_index=True, default='direct', max_length=16),
        ),
    ]
